version: "2"
services:
  server:
    image: gcr.io/jenkinsxio/hugo-extended:0.65.3-6
    command: ["hugo", "server", "-s", "/src", "-D", "--bind", "0.0.0.0", "--ignoreCache"]
    volumes:
      - .:/src
    ports:
      - "1313:1313"
  spellchecker:
    image: tmaier/markdown-spellcheck:latest
    command: "--en-us --ignore-numbers --ignore-acronyms --report \"content/**/*.md\""
    volumes:
      - .:/workdir
  linkchecker:
    image: wjdp/htmltest:v0.12.0
    command: "htmltest -l0 -s -c /test/.htmltest.yml"
    volumes:
      - .:/test
